### ISSUE TITLE
Baldurs Gate 3 - patch 7 profile update

### ISSUE THREAD

**Issue by Deshke** [Nexus-Mods/Vortex#11062]
somehow Larian Studios decided that with patch 7 the playerProfile location with the Mods folder is now in 

`%APPDATA%\Local\Larian Studios\Baldur's Gate 3`

same folder structure, but no longer in `Documents\Larian Studios`

![image](https://user-images.githubusercontent.com/1473225/154151031-46f8f6c6-f215-4b7e-9490-8ab0308c81c9.png)

**Comment by TanninOne** [comment]
Thanks for the info!

**Comment by TanninOne** [comment]
fixed by https://github.com/Nexus-Mods/vortex-games/commit/18c29306aea8d83f702da36037999e3403586503

**Comment by Deshke** [comment]
@TanninOne is there a way to manually update the vortex extension?

**Comment by beodawn1** [comment]
It's not fixed quite yet. Vortex is seeing only profiles from a year ago in my OneDrive account in Windows 10. It cannot find the actual new install of Baldur's Gate 3 (fresh install, regular steam location on c drive) and it refuses to locate any profiles. I deleted the ones in One Drive and it Still only sees the ones that Were in One Drive. It cannot find the new profiles at all.
