### ISSUE TITLE
Network Connection Offline Bug

### ISSUE THREAD

**Issue by BauderLikeWater** [Nexus-Mods/Vortex#18680]
**Bug Description**
"Network is offline" appears intermittently. I've launched as administrator and verified that the app is allowed through my firewall. Cannot seem to figure out what is causing the issue. Would say that this issue happens 9 out of 10 launches and there is no button to try and force a reconnect. App is able to view "Knowledge base" window, indicating some sort of network connection.

App still reports that it is up to date upon launch despite not(?) having a network connection.

**Expected behavior**
Network should connect when internet connection is available and Nexus network is online.

**Platform**
 - OS: Windows 11
 - Vortex Version 1.15.2

**Comment by IDCs** [comment]
Hi @BauderLikeWater, the site and API had issues last night, should be fixed now.

There is nothing we (Vortex support) can do with connectivity issues - it's better to report this on the forums or to support@nexusmods.com when it happens.

**Comment by BauderLikeWater** [comment]
Hi @IDCs 

This issue is still not resolved. This has been ongoing for the past 2+ weeks. I can successfully ping the API via powershell. When I initiate a Vortex download, I receive a "Mod download failed" with the only context being "network disconnected: getModInfo". 

I've also attempted to login with a fresh Vortex installation to see if there was some contributing issue. The "Network is Offline" persists even with a brand new installation with my Vortex %AppData% cleared.

**Comment by IDCs** [comment]
Hey @BauderLikeWater, I'm afraid this is not a Vortex issue - it's a connectivity issue and we can't help with those. @Pickysaurus might know who to forward this to or additional debugging steps you may take.

**Comment by Pickysaurus** [comment]
It's a PC configuration issue. Something is completely blocking Vortex from communicating with the internet. Check your local security/firewall apps.

**Comment by Abweed** [comment]
I'm facing the same problem. Did anyone find a solution? Tried everything almost.

**Comment by BauderLikeWater** [comment]
> I'm facing the same problem. Did anyone find a solution? Tried everything almost.

I never figured it out and still experience this behavior to this day. I did discover a workaround, however; open Vortex, put Windows to sleep, and then wake your PC and check Vortex. This works for me more often than not, but I also typically let it sleep for at least 10 minutes before I come back. Unless I’m adding mods, I’m just playing offline. Hope this helps.
