### ISSUE TITLE
Game 'falloutnv not found'

### ISSUE THREAD

**Issue by Sandvichero** [Nexus-Mods/Vortex#973]
When downloading off Nexus this error shows
on Testing branch

**Comment by bcairns** [comment]
Seeing this with SkyrimVR too, when trying to click Nexus links.

```
Download failed
Game 'skyrimvr' not found
```

**Comment by TanninOne** [comment]
Already found this.

**Comment by ArtaiosGreybark** [comment]
Not sure if Tannin means that he found the bug but to answer the question regardless: It's not in debug but the official 16.2 Testing release. The notification is the one that appears at the bottom right on Windows 10 where it normally notifies you of a started download.

**Comment by IDCs** [comment]
Issue should be fixed in future testing releases.

**Comment by Isvvc** [comment]
I am still getting this issue on 16.12, specifically for Skyrim VR and Fallout 4 VR. I don't get it with Skyrim, so I would assume it's an issue with the VR derivatives of games since they're downloading from the same Nexus as another game. 

It appears that I get this error when I have the main game (Fallout 4 or Skyrim Special Edition) extension disabled, but when I have it enabled, it refuses to download at all, with no error given.
